services:
  ui:
    image: photoflux:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.photoflux-workspace.rule=Host(`photoflux.services.ozoniuss.com`)
      - traefik.http.routers.photoflux-workspace.entrypoints=web

networks:
  proxy:
    name: proxy
    external: true
